branches:
  - '+([0-9])?(.{+([0-9]),x}).x'
  - master
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true

repositoryUrl: https://github.com/nickderobertis/github-actions-semantic-release-example

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - ["@semantic-release/npm", {
      "npmPublish": false,
    }]
  - "@semantic-release/github"